### PR TITLE
Enforce refresh token clean-up

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Remove the stale user info whenever the refresh process fails so the user is forced to authenticate again from scratch. This will force obtaining a new refresh token, before the broken token would remain unchanged when loggin in via JWT.

Also check the validity of the access token so the refresh does not need to happen if the user has a valid token in place.

---

**Related issue :**

### CODE REVIEW

**Review by andrea-manzi — COMMENTED** [review]
looks good ! @valtri can you give it a try on the testing installation?

**Comment by valtri** [comment]
There is some unrelated problem in JWT wrapper with oauthenticator 16.3.0 (from the older changes):

```
To use the fastapi command, please install "fastapi[standard]":

	pip install "fastapi[standard]"

Traceback (most recent call last):
  File "/usr/local/bin/fastapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fastapi/cli.py", line 12, in main
    raise RuntimeError(message)  # noqa: B904
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: To use the fastapi command, please install "fastapi[standard]":

	pip install "fastapi[standard]"
```

But it works with the oauthenticator 16.1.0.

**Comment by enolfc** [comment]
> There is some unrelated problem in JWT wrapper with oauthenticator 16.3.0 (from the older changes):
> 
> ```
> To use the fastapi command, please install "fastapi[standard]":
> 
> 	pip install "fastapi[standard]"
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/fastapi", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/fastapi/cli.py", line 12, in main
>     raise RuntimeError(message)  # noqa: B904
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: To use the fastapi command, please install "fastapi[standard]":
> 
> 	pip install "fastapi[standard]"
> ```
> 
> But it works with the oauthenticator 16.1.0.

Fixed

**Review by valtri — APPROVED** [review]
Looks good!

**Pull request merged**
