### PR TITLE
Improve EGI looks

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Make it look more EGI:
- Add title to the page
- Add EGI logo
- Improve code

---

**Related issue :** https://jira.egi.eu/browse/IMSSSB-110

### CODE REVIEW

**Review by andrea-manzi — APPROVED** [review]
i checked the screenshot on the attached ticket and it looks ok!

**Comment by enolfc** [comment]
> i checked the screenshot on the attached ticket and it looks ok!

@valtri if you can deploy in your test instance to check that it works fine with k8s it would be appreciated (I tested just locally)

**Comment by enolfc** [comment]
Works as expected. Should be good to go to prod

**Comment by valtri** [comment]
Test instance is working too, both welcome and auth error pages with new logo and favicon.

**Pull request merged**
