### PR TITLE
Avoid setting up onedata if not available

### PR DESCRIPTION
**Pull request by enolfc**
# Summary

Does not try to configure all the onedata stuff if there is information missing. Fixes monitoring 

---

**Related issue :**

### CODE REVIEW

**Review by valtri — DISMISSED** [review]
Tested and it works!
We can consider to check `auth_state is None` in `auth_state_hook()` too (just error messages in log).

**Comment by enolfc** [comment]
> Tested and it works!
> We can consider to check `auth_state is None` in `auth_state_hook()` too (just error messages in log).

I understand auth_state should never be `None` here, but the different variables may be.

**Comment by enolfc** [comment]
> > Tested and it works!
> > We can consider to check `auth_state is None` in `auth_state_hook()` too (just error messages in log).
> 
> I understand auth_state should never be `None` here, but the different variables may be.

ok, saw now your comment in Slack... let's fix this

**Review by valtri — APPROVED** [review]
Looks good!

**Pull request merged**
